### ISSUE TITLE
[bug] prevent eyny.com login popup

### ISSUE THREAD

**Issue by craftwar** [tsaiid/gm-i-am-over-18#1]
If script is on, clicking login never pops up login window. 
Work around: disable login temporarily when login.

btw homepageURL should be set to this site?

**Comment by tsaiid** [comment]
Thx. the homepageURL had been set to this site. 
The login popup bug may be related to the incorrect placed jQuery.noConflict workaround in the window load event listener. After updating to v0.2.20160821, this should be fixed.
