### ISSUE TITLE
eyny login problem

### ISSUE THREAD

**Issue by craftwar** [tsaiid/gm-i-am-over-18#15]
This script changes $, result in security question can't run original $. It makes login impossible if security question is set.
I don't know how to solve this is best. Maybe we should remove JQuery, use native selector instead.

**Comment by tsaiid** [comment]
Do not understand what you mean. I can login to eyny and the click method still works well. However, it is not a bad idea to replace jQuery with native selector.

**Comment by craftwar** [comment]
security question uses javascript to produce input field dynamically. function name is $
![image](https://user-images.githubusercontent.com/16416710/40127676-820f4dd0-5962-11e8-95ea-3809466d0232.png)
firefox and chrome
If I disable this script, answer field to security question will appear.
![image](https://user-images.githubusercontent.com/16416710/40127892-f9bdf1d8-5962-11e8-8c3f-5af711d807e6.png)

`
<select id="loginquestionid_Lq1qf" tabindex="1" width="213" name="questionid" onkeyup="this.onKeyUp=this.onchange();" onchange="if($('loginquestionid_Lq1qf').value > 0) {$('loginanswer_row_Lq1qf').style.display='';} else {$('loginanswer_row_Lq1qf').style.display='none';}"><option value="0">安全提問(未設置請忽略)</option><option value="1">母親的名字</option><option value="2">爺爺的名字</option><option value="3">父親出生的城市</option><option value="4">你其中一位老師的名字</option><option value="5">你個人計算機的型號</option><option value="6">你最喜歡的餐館名稱</option><option value="7">駕駛執照最後四位數字</option></select>
`

**Comment by tsaiid** [comment]
![image](https://user-images.githubusercontent.com/4302689/40131295-280b33ee-596c-11e8-945e-8fcf1e62531b.png)

I don't have such error, and the answer input of security question appeared. I use Chrome 66 on Win10.

**Comment by craftwar** [comment]
userscript manager? I use Violentmonkey

**Comment by tsaiid** [comment]
I use [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=zh-TW).

**Comment by craftwar** [comment]
先關掉，網站或是extension改版後沒發生，#17修正前就沒遇到了
