### ISSUE TITLE
firefox 下 Greasemonkey 安裝顯示錯誤

### ISSUE THREAD

**Issue by smailzhu** [tsaiid/gm-i-am-over-18#16]
在firefox addon [Greasemonkey](https://addons.mozilla.org/zh-TW/firefox/addon/greasemonkey/) 安裝會顯示錯誤

錯誤訊息

> 使用者指令稿下載失敗
> 忽略 @match 模式 *://*.blogspot.*/* 因為：\nError: @match: Invalid host specified.

**Comment by smailzhu** [comment]
根據 [code裡面的 L98](https://github.com/tsaiid/gm-i-am-over-18/blob/master/gm-i-am-over-18.user.js#L98)
https://gist.github.com/obeattie/362589
原作者的 code
他用  `// @match           *://*.blogspot.com/*` 就不會有error了

**Comment by tsaiid** [comment]
的確，用 @match 比用 @include 限制多一些: [ref](https://developer.chrome.com/extensions/match_patterns)

> If '*' is in the host, it must be the first character

目前看起來 blogspot 應該會把所有的 url 導到 blogspot.com，所以已經改了。
