### ISSUE TITLE
Use webhook to auto publish updated script

### ISSUE THREAD

**Issue by craftwar** [tsaiid/gm-i-am-over-18#21]
The version on openuserjs is wrong.
// @version         0.2.20180521

You should use webhook, it will publish after every git commit.

**Comment by tsaiid** [comment]
I had already set the webhook, but it failed to update for unknown reason and returned HTTP 451. Just then, I deleted the old webhook and re-add a new one. It seems working. I will check if it works after next commit.

**Comment by tsaiid** [comment]
I just merged a pull request, and the webhook worked. I will close this issue.
